ServerEvents.recipes((x) => {
  x.recipes.createmetallurgy.melting(
    `createmetallurgy:molten_tungsten`,
    `createmetallurgy:dirty_wolframite_dust`,
    30,
    'heated',
  );
  x.recipes.createmetallurgy.melting(
    `createmetallurgy:molten_aluminum`,
    `kubejs:aluminum_dust`,
    30,
    'heated',
  );
  x.recipes.createmetallurgy.melting(
    `createmetallurgy:molten_silver`,
    `kubejs:silver_dust`,
    30,
    'heated',
  );
  x.recipes.create.pressing(
    'createmetallurgy:tungsten_sheet',
    `createmetallurgy:tungsten_ingot`,
  );
});
